### ISSUE TITLE
No such file  rsp_alsa_api.h

### ISSUE THREAD

**Issue by UW5EHX** [CrumResearch/RSPALSAServer#1]
Hi Crum. 
I am trying to compile this project.
i'm having problems at the "make" step
I need the file "rsp_alsa_api.h"
Thanks for your work!

**Comment by ON5HB** [comment]
You need to install the 3.xx API from SDRplay.com, as that contains the parts between this software and the receiver.

https://www.sdrplay.com/softwarehome/

**Comment by CrumResearch** [comment]
Thanks for the interest, guys!  This code was useful as a development milestone, but it is not needed anymore as we have evolved to faster and more capable methods with higher sampling rate, 768K samples/second.  See some related discussion at
http://www.sdrutah.org/info/latestnews.html

**Comment by CrumResearch** [comment]
Closing this issue and may delete this repository in the future;  I'll see about creating a new repository as this R&D is evolving and relatively fast-moving.

**Comment by UW5EHX** [comment]
hi Bas. I figured out to put API 3.07, but this did not solve the problem with "rsp_alsa_api.h"
thanks Gary. I'll be waiting for the release.
